holster_config = {}

holster_config = {
    guns = { 'autoshotgun', 'assaultrifle', 'grenadelauncher', 'nucleargun', 'flamerunique', 'flamer', 'smg', 'smgunique', 'shotgun', 'shotgununique', 'divingknife', 'divingknifeunique', 'revolver', 'handcannon' , 'stungun', 'harpoongun', 'stunbaton', 'boardingaxe'},
    clothes = { 'securityuniform1', 'securityuniform2', 'securityuniform3' },
    sprites = {
        autoshotgun = [[<sprite name="Autoshogun Worn Holster" texture="Content/Items/JobGear/TalentGear.png" canbehiddenbyotherwearables="false" rotation="90" inheritlimbdepth="false" depth="0.6" sourcerect="308,1,152,61" limb="Torso" ignorelimbscale="true" scale="0.62" origin="0.5,0.9" />]],
        assaultrifle = [[<sprite name="Assault Rifle Worn Holster" texture="Content/Items/JobGear/TalentGear.png" canbehiddenbyotherwearables="false" rotation="90" inheritlimbdepth="false" depth="0.6" sourcerect="276,63,233,62" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        assaultrifle_fix = [[<sprite name="Assault Rifle Worn Holster" texture="Content/Items/JobGear/TalentGear.png" canbehiddenbyotherwearables="false" rotation="90" inheritlimbdepth="false" depth="0.6" sourcerect="276,63,233,62" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        grenadelauncher = [[<sprite name="Grenade Launcher Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,244,186,65" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        nucleargun = [[<sprite name="Nuclear Gun Worn Holster" texture="Content/Items/JobGear/TalentGear.png" canbehiddenbyotherwearables="false" rotation="90" inheritlimbdepth="false" depth="0.6" sourcerect="270,127,240,66" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        flamerunique = [[<sprite name="Flamer Unique Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="263,193,150,87" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        flamer = [[<sprite name="Flamer Worn Holster" texture="Content/Items/Tools/tools.png" canbehiddenbyotherwearables="false" sourcerect="154,22,158,77" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,0.8" />]],
        smg = [[<sprite name="SMG Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,121,144,80" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,0.9" />]],
        smgunique = [[<sprite name="SMG Unique Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="263,135,145,56" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,0.9" />]],
        shotgun = [[<sprite name="Shotgun Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,65,185,54" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,1.0" />]],
        shotgununique = [[<sprite name="Shotgun Unique Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="262,70,184,51" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,1.0" />]],
        divingknife = [[<sprite name="Diving Knife Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="183,203,66,16" rotation="270" inheritlimbdepth="false" depth="0.1" limb="Torso" scale="0.5" origin="-0.5,0.3" />]],
        divingknifeunique = [[<sprite name="Diving Knife Unique Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="186,183,63,16" rotation="270" inheritlimbdepth="false" depth="0.1" limb="Torso" scale="0.5" origin="-0.5,0.3" />]],
        revolver = [[<sprite name="Revolver Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,418,76,41" rotation="270" inheritlimbdepth="false" depth="0.1" limb="Torso" scale="0.5" origin="-0.5,0.3" />]],
        handcannon = [[<sprite name="Handcannon Worn Holster" texture="Content/Items/Jobgear/TalentGear.png" canbehiddenbyotherwearables="false" sourcerect="0,256,111,56" rotation="270" inheritlimbdepth="false" depth="0.1" limb="Torso" scale="0.5" origin="-0.3,0.3" />]],
        stungun = [[<sprite name="Stungun Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,368,83,47" rotation="270" inheritlimbdepth="false" depth="0.1" limb="Torso" scale="0.5" origin="-0.3,0.3" />]],
        harpoongun = [[<sprite name="Harpoon Gun Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,203,181,39" rotation="90" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.5,1.1" />]],
        stunbaton = [[<sprite name="Stun Baton Worn Holster" texture="Content/Items/Weapons/weapons_new.png" canbehiddenbyotherwearables="false" sourcerect="0,0,191,63" rotation="275" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.3,0.2" />]],
        boardingaxe = [[<sprite name="Boarding Axe Worn Holster" texture="Content/Items/JobGear/TalentGear.png" canbehiddenbyotherwearables="false" sourcerect="1,425,164,53" rotation="270" inheritlimbdepth="false" depth="0.6" limb="Torso" scale="0.5" origin="0.6,-0.4" />]],
    }
}

return holster_config